version: '3.8'

services:
  mariadb:
    image: mariadb:inc
    build: ./requirements/mariadb
    volumes:
     - mariadb-data:/var/lib/mysql
    networks:
      - inception
    restart: always
    env_file:
      - .env


# On Linux, the default location for Docker data is /var/lib/docker/volumes/
volumes:
#  wordpress-data:
#    driver: local
  mariadb-data:
    driver: local

networks:
  inception:
