version: '3.8'

services:
  nginx:  #container name
    image: nginx:inc
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - inception
    restart: always
  
  wordpress:
    image: wordpress:inc
    build: ./requirements/wordpress
    volumes:
     - wordpress-data:/var/www/html
    networks:
      - inception
    restart: always


volumes:
  wordpress-data:
    driver: local

networks:
  inception:
