version: '3.8'

services:
  nginx:  #container name
    depends_on:
      - wordpress
    image: nginx:inc
    build: ./requirements/nginx
    ports:
      - 443:443 #the only port allowed 
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - inception
    restart: unless-stopped
  
  wordpress:
    depends_on:
      mariadb:
        condition: service_healthy
    image: wordpress:inc
    build: ./requirements/wordpress
    volumes:
     - wordpress-data:/var/www/html
    networks:
      - inception
    restart: unless-stopped
    env_file:
    - .env
  
  mariadb:
    image: mariadb:inc
    build: ./requirements/mariadb
    volumes:
     - mariadb-data:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: "mysql -u$MYSQL_USER -p$MYSQL_PASSWORD -e 'select 1;'"
      interval: 1s
      retries: 20


# On Linux, the default location for Docker data is /var/lib/docker/volumes/
volumes:
  mariadb-data:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/qtran/data/mariadb
      o: bind
  wordpress-data:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/qtran/data/wordpress
      o: bind

networks:
  inception:
